language: groovy

jdk:
- oraclejdk8

before_install:
- git --version
- echo $GRADLE_OPTS
- export GRADLE_OPTS='-Dorg.gradle.daemon=true'

install:
- ./gradlew assemble

script:
- set -e
- ./gradlew check --info --stacktrace --continue
- source src/main/resources/gradle/setGitVariables.sh
- ./gradlew release -Prelease.disableRemoteCheck -Prelease.localOnly --info --stacktrace
- ./gradlew finalizeRelease publishUploadedArtifacts -PbintrayUser=${BINTRAY_USER} -PbintrayKey=${BINTRAY_API_KEY} --info --stacktrace

env:
  global:
  - TERM=dumb
  - secure: hSQ6fPa91G6sJgwoPor3mkklrMbSFSVn5d+JBoEfZ7aVwEi3phPx0ZcgMesJKM09o3KPQP8uDo1vZdXb8aE2cNj+5oNYrnDUjwil3EylsB5oxgA8iMR/ZMQY7nJUIWBuL13PCSeNPplO8D8hzrpgPBCSic6kwYVKLGr5Cxg03xY=
  - secure: Kws8DKJd4CoadVTgRE73dpu001feo0/28ZLPNhGDnAGeOJ8y2jpSlmgm2xNzap9+U1e/TOhvQ8hlqASv8rpMrWfvDZtmbwYPy9KR8uJfU0Zf/g7wZ5swGGlR9IxVT4XlBIUsqPHNyOQqQ5I4nbYQowuoRuasU6jDV49dMOQL/Yg=
  - secure: FVAjUEYUPUwE6l+nG0P6GcCSz9X+PL9I6NNhjOEdPMb4FuMV2pN0rKuL6hS2tC8EYaBqP6OPtvWGsO4H/GSlq9KjaNq2VhIIEdPbNzZaoytiZij0cExVE7GIlKQYQTRodF/s2B4ady4NvMigRzP+fz+IX5q/9UG6eFMadzp8m44=
