language: groovy
jdk:
- oraclejdk8
before_install:
- git --version
- echo $GRADLE_OPTS
- export GRADLE_OPTS='-Dorg.gradle.daemon=true'
install:
- "./gradlew assemble"
script:
- set -e
- "./gradlew check --info --stacktrace --continue"
- source src/main/resources/gradle/setGitVariables.sh
- "./gradlew release -Prelease.disableRemoteCheck -Prelease.localOnly --info --stacktrace"
- "./gradlew finalizeRelease publishUploadedArtifacts -PbintrayUser=${BINTRAY_USER}
  -PbintrayKey=${BINTRAY_API_KEY} --info --stacktrace"
env:
  global:
  - TERM=dumb
  - secure: FZZlWJ1of5OTagbwK7cD+yGe4sKMCKLt+GzWdxJxIEDYkpcy3GWkrUkXOqnXBxEkUCPIBpxAsWgPvf2k6zFO/6m3NQ8K/2q28aedjV7etz6HZC5OeIhJalWpMiJh1VzYRmKC9J41qJ/SrMOY2MBASACNROt54EteNez+YVVAleo=
  - secure: Kws8DKJd4CoadVTgRE73dpu001feo0/28ZLPNhGDnAGeOJ8y2jpSlmgm2xNzap9+U1e/TOhvQ8hlqASv8rpMrWfvDZtmbwYPy9KR8uJfU0Zf/g7wZ5swGGlR9IxVT4XlBIUsqPHNyOQqQ5I4nbYQowuoRuasU6jDV49dMOQL/Yg=
  - secure: kXVOIaAD5i1fLm+J5LXJpHBJeYBkHMeq8qcjm2WBdGwX/kr0zqzRDy0DT3dxo2/JQ3okP9Ai3oPUsjs70xs7jMy3GVIy6idfUEz4gZjq64FYJYvkXmsSV8vynyTSKwdZ0nooGBtRrRCqc8dV6yI1Vr7UQ5MBm06OIqUVFoCYmIw=
  - secure: ZD5abT8rO/w4g1IR3pen/JMTF1Yy6djBmbDkWAUQmDI7TzMmIaUTQvgiU+par0KhaGIGFytl/M+MRSjeiz0vp/SEkplW6+kjuggBMl0srdurNhyXVHgo5dyPrmyRyyDsZOxt8mvFZrl7vsoqEW8Bir/kTSHzyhcNegOmKbGw9Ow=
